name:                heaven
version:             0.1.0.0

extra-source-files:
- README.md

synopsis:            Heaven server
description:         Please see the README on GitHub at <https://github.com/kofoednielsen/pass/blob/main/heaven#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0.2
- websockets >= 0.12.7.3
- aeson >= 2.1.2.1
- base-compat >= 0.12.3
- bytestring >= 0.11.4.0
- MissingH >= 1.6.0.0
- random >= 1.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

pkgconfig-depends: zlib

executables:
  heaven:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - heaven
