apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    numerical: {}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: snake
spec:
  imageRepositoryRef:
    name: snake
  policy:
    numerical: {}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sketch
spec:
  imageRepositoryRef:
    name: sketch
  policy:
    numerical: {}
      
