apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    semver:
      range: x.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: snake
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: snake
  policy:
    semver:
      range: x.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sketch
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sketch
  policy:
    semver:
      range: x.x.x
