name: build

on:
  push:
    branches:
      - 'main'
    paths:
      - './hell'
      - './sketch'
      - './frontend'
      - './heaven'
      - './snake'
      - './star'
jobs:
  version-job:
    runs-on: ubuntu-latest
    outputs:
      version-output: ${{ steps.version-step.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Retrieve version
        id: version-step
        run: |
          echo version=$(git log --perl-regexp --author='^((?!fluxcdbot).)*$' --oneline | wc -l) >> "$GITHUB_OUTPUT"
  build-and-push-image:
    needs: version-job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./sketch
            image: ghcr.io/kofoednielsen/pass-sketch
          - context: ./snake
            image: ghcr.io/kofoednielsen/pass-snake
          - context: ./frontend
            image: ghcr.io/kofoednielsen/pass-frontend
          - context: ./hell
            image: ghcr.io/kofoednielsen/pass-hell
          - context: ./heaven
            image: ghcr.io/kofoednielsen/pass-heaven
          - context: ./star
            image: ghcr.io/kofoednielsen/pass-star
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image Drill4Net.Agent.Service
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: "${{ matrix.image }}:${{needs.version-job.outputs.version-output}}"
